table constructor_standings
	lineageTag: 5c1b128f-819b-4d3d-b547-1c63bea900dd

	column constructorStandingsId
		dataType: int64
		formatString: 0
		lineageTag: a0082fd0-742d-496f-928d-6ea7fd320c79
		summarizeBy: count
		sourceColumn: constructorStandingsId

		annotation SummarizationSetBy = Automatic

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: ed26a3d6-8d4d-424a-9f18-01d05855ecb7
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column constructorId
		dataType: int64
		formatString: 0
		lineageTag: 77e7c4bd-b4ff-4622-b0ee-f07fa103870a
		summarizeBy: none
		sourceColumn: constructorId

		annotation SummarizationSetBy = Automatic

	column points
		dataType: int64
		formatString: 0
		lineageTag: a08e1f68-ef61-45ec-adb8-dde28f359fa9
		summarizeBy: sum
		sourceColumn: points

		annotation SummarizationSetBy = Automatic

	column position
		dataType: int64
		formatString: 0
		lineageTag: b63fad59-f473-4126-a2da-d5e55e28a15e
		summarizeBy: sum
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column positionText
		dataType: string
		lineageTag: a76aa35b-9fb9-4285-a90f-b1921410f968
		summarizeBy: none
		sourceColumn: positionText

		annotation SummarizationSetBy = Automatic

	column wins
		dataType: int64
		formatString: 0
		lineageTag: 96e7c7d1-4219-4391-977f-2cd6652ad305
		summarizeBy: sum
		sourceColumn: wins

		annotation SummarizationSetBy = Automatic

	partition constructor_standings = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("D:\Study\Portfolio_BI\Formula 1 Race Data\dataset\constructor_standings.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"constructorStandingsId", Int64.Type}, {"raceId", Int64.Type}, {"constructorId", Int64.Type}, {"points", Int64.Type}, {"position", Int64.Type}, {"positionText", type text}, {"wins", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

