table constructor_results
	lineageTag: efa270dc-b1db-4261-88da-8d9bd91ca52c

	column constructorResultsId
		dataType: int64
		formatString: 0
		lineageTag: bb75479e-ac4d-4a99-a92b-36c37921649f
		summarizeBy: count
		sourceColumn: constructorResultsId

		annotation SummarizationSetBy = Automatic

	column raceId
		dataType: int64
		formatString: 0
		lineageTag: 49b6365d-cf3c-4535-9c6f-706e0b647c38
		summarizeBy: none
		sourceColumn: raceId

		annotation SummarizationSetBy = Automatic

	column constructorId
		dataType: int64
		formatString: 0
		lineageTag: e80dc2c3-85e6-4871-9c5b-7961ff24ee81
		summarizeBy: none
		sourceColumn: constructorId

		annotation SummarizationSetBy = Automatic

	column points
		dataType: int64
		formatString: 0
		lineageTag: 32cd1e46-88fe-47d0-a275-5222f8f5e1ee
		summarizeBy: sum
		sourceColumn: points

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: f3ec6ce6-c0e0-414e-9510-019cc67b6b3e
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	partition constructor_results = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("D:\Study\Portfolio_BI\Formula 1 Race Data\dataset\constructor_results.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"constructorResultsId", Int64.Type}, {"raceId", Int64.Type}, {"constructorId", Int64.Type}, {"points", Int64.Type}, {"status", type text}}),
				    #"Valor Substituído" = Table.ReplaceValue(#"Tipo Alterado","\N","",Replacer.ReplaceText,{"status"})
				in
				    #"Valor Substituído"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

