table status
	lineageTag: d248e0d7-0a67-4a43-96be-8e18b3b28c04

	column statusId
		dataType: int64
		formatString: 0
		lineageTag: 8555c3c8-d1fc-47e2-8031-bd11e848aad8
		summarizeBy: none
		sourceColumn: statusId

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: c09f1856-784f-41dd-9431-e2c6532b294b
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	partition status = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("D:\Study\Portfolio_BI\Formula 1 Race Data\dataset\status.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"statusId", Int64.Type}, {"status", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

